[project]
name = "llm-converse"
version = "0.1.0"
description = "Converse with someone or watch a conversation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.57.1",
    "gremllm>=0.2.0",
    "llm-claude-3>=0.11",
    "rich>=14.0.0",
    "typer>=0.16.0",
]
